# Generated by Django 4.2.6 on 2023-10-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Party time')], default='PT', max_length=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
