# Generated by Django 4.2.6 on 2023-10-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pic',
            field=models.ImageField(default='', upload_to='jobs/'),
            preserve_default=False,
        ),
    ]
